[package]
name = "robo1_main"
version = "0.1.0"
edition = "2021"

[dependencies]
motor_controller = { git = "https://github.com/nityc-d-robo/motor_controller", rev="4d09feb4c32cad8f191f9d8d1ae19780f4e08c40" }
serde_json = "1.0.55"
serde = { version = "1.0.100", features = [ "derive" ] }